<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.12" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\App.Domain.AppServices\App.Domain.AppServices.csproj" />
		<ProjectReference Include="..\App.Domain.Core\App.Domain.Core.csproj" />
		<ProjectReference Include="..\App.Domain.Services\App.Domain.Services.csproj" />
		<ProjectReference Include="..\App.InfraAccess.EFCore\App.InfraAccess.EFCore.csproj" />
		<ProjectReference Include="..\App.Infrastructure.Dapper\App.Infrastructure.Dapper.csproj" />
		<ProjectReference Include="..\Framework\Framework.csproj" />
	</ItemGroup>

</Project>
