// <auto-generated />
using System;
using App.Infrastructure.EFCore.DataBase.Common;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace App.Infrastructure.EFCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("App.Domain.Core.Entites.Service.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImagePath = "\\Images\\Categories\\tasisat1.jpg",
                            IsDeleted = false,
                            Title = "تاسیسات"
                        },
                        new
                        {
                            Id = 3,
                            ImagePath = "\\Images\\Categories\\3 فعلی.jpg",
                            IsDeleted = false,
                            Title = "نظافت"
                        },
                        new
                        {
                            Id = 4,
                            ImagePath = "\\Images\\Categories\\zibaii.jpg",
                            IsDeleted = false,
                            Title = "زیبایی"
                        },
                        new
                        {
                            Id = 5,
                            ImagePath = "\\Images\\Categories\\tamirat.jpg",
                            IsDeleted = false,
                            Title = "تعمیرات اشیا"
                        },
                        new
                        {
                            Id = 6,
                            ImagePath = "\\Images\\Categories\\6 فعلی (2).jpg",
                            IsDeleted = false,
                            Title = " خودرو و حمل بار"
                        },
                        new
                        {
                            Id = 7,
                            ImagePath = "\\Images\\Categories\\7 فعلی.jpg",
                            IsDeleted = false,
                            Title = "سلامت"
                        },
                        new
                        {
                            Id = 8,
                            ImagePath = "\\Images\\Categories\\8 فعلی.png",
                            IsDeleted = false,
                            ParentId = 1,
                            Title = "برقکاری"
                        },
                        new
                        {
                            Id = 9,
                            ImagePath = "\\Images\\Categories\\9 فعلی.png",
                            IsDeleted = false,
                            ParentId = 1,
                            Title = "لوله کشی"
                        },
                        new
                        {
                            Id = 10,
                            ImagePath = "\\Images\\Categories\\10 فعلی.png",
                            IsDeleted = false,
                            ParentId = 1,
                            Title = "سرمایش و گرمایش"
                        },
                        new
                        {
                            Id = 14,
                            ImagePath = "\\Images\\Categories\\916efcce-9fdb-45ac-9d9b-8b821748a1f5-category_image (2).png",
                            IsDeleted = false,
                            ParentId = 3,
                            Title = "نظافت و پذیرایی"
                        },
                        new
                        {
                            Id = 15,
                            ImagePath = "\\Images\\Categories\\15فعلی.png",
                            IsDeleted = false,
                            ParentId = 3,
                            Title = "شستشو"
                        },
                        new
                        {
                            Id = 16,
                            ImagePath = "\\Images\\Categories\\16 فعلی.png",
                            IsDeleted = false,
                            ParentId = 3,
                            Title = "کارواش و دیتیلینگ"
                        },
                        new
                        {
                            Id = 17,
                            ImagePath = "\\Images\\Categories\\17.png",
                            IsDeleted = false,
                            ParentId = 4,
                            Title = "زیبایی بانوان"
                        },
                        new
                        {
                            Id = 18,
                            ImagePath = "\\Images\\Categories\\18.png",
                            IsDeleted = false,
                            ParentId = 4,
                            Title = "پیرایش و زیبایی آقایان"
                        },
                        new
                        {
                            Id = 19,
                            ImagePath = "\\Images\\Categories\\19.png",
                            IsDeleted = false,
                            ParentId = 4,
                            Title = "تندرستی و ورزش"
                        },
                        new
                        {
                            Id = 20,
                            ImagePath = "\\Images\\Categories\\20.png",
                            IsDeleted = false,
                            ParentId = 5,
                            Title = "نصب و تعمیر لوازم خانگی"
                        },
                        new
                        {
                            Id = 21,
                            ImagePath = "\\Images\\Categories\\21.png",
                            IsDeleted = false,
                            ParentId = 5,
                            Title = "خدمات کامپیوتری"
                        },
                        new
                        {
                            Id = 22,
                            ImagePath = "\\Images\\Categories\\22.png",
                            IsDeleted = false,
                            ParentId = 5,
                            Title = "تعمیرات موبایل"
                        },
                        new
                        {
                            Id = 23,
                            ImagePath = "\\Images\\Categories\\23.png",
                            IsDeleted = false,
                            ParentId = 6,
                            Title = "خدمات و تعمیرات خودرو"
                        },
                        new
                        {
                            Id = 24,
                            ImagePath = "\\Images\\Categories\\24.png",
                            IsDeleted = false,
                            ParentId = 6,
                            Title = "باربری و جابجایی"
                        },
                        new
                        {
                            Id = 25,
                            ImagePath = "\\Images\\Categories\\25.png",
                            IsDeleted = false,
                            ParentId = 7,
                            Title = "پرشکی و پرستاری"
                        },
                        new
                        {
                            Id = 26,
                            ImagePath = "\\Images\\Categories\\26.png",
                            IsDeleted = false,
                            ParentId = 7,
                            Title = "حیوانات خانگی"
                        });
                });

            modelBuilder.Entity("App.Domain.Core.Entites.Service.ExpertHouseWork", b =>
                {
                    b.Property<int>("ExpertId")
                        .HasColumnType("int");

                    b.Property<int>("HouseWorkId")
                        .HasColumnType("int");

                    b.HasKey("ExpertId", "HouseWorkId");

                    b.HasIndex("HouseWorkId");

                    b.ToTable("ExpertHouseWorks");
                });

            modelBuilder.Entity("App.Domain.Core.Entites.Service.HouseWork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("BasePrice")
                        .IsRequired()
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ViewCount")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("HouseWorks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 5000m,
                            CategoryId = 10,
                            Description = "نیاز به توضیحات تکمیلی مشکل",
                            ImagePath = "\\Images\\HomeServices\\1h.jpg",
                            IsDeleted = false,
                            Title = "تعمیر و سرویس پکیج"
                        },
                        new
                        {
                            Id = 2,
                            BasePrice = 3000m,
                            CategoryId = 10,
                            Description = "",
                            ImagePath = "\\Images\\HomeServices\\2h.jpg",
                            IsDeleted = false,
                            Title = "تعمیر و سرویس آبگرمکن"
                        },
                        new
                        {
                            Id = 3,
                            BasePrice = 3500m,
                            CategoryId = 10,
                            Description = "",
                            ImagePath = "\\Images\\HomeServices\\3h.jpg",
                            IsDeleted = false,
                            Title = "نصب و تعمیر رادیاتور شوفاژ"
                        },
                        new
                        {
                            Id = 4,
                            BasePrice = 4000m,
                            CategoryId = 10,
                            Description = "پرتقاضا",
                            ImagePath = "\\Images\\HomeServices\\4h.jpg",
                            IsDeleted = false,
                            Title = "تعمیر و سرویس کولر آبی"
                        },
                        new
                        {
                            Id = 5,
                            BasePrice = 2500m,
                            CategoryId = 10,
                            Description = "",
                            ImagePath = "\\Images\\HomeServices\\5h.jpg",
                            IsDeleted = false,
                            Title = "تعمیر و نصب کولر گازی"
                        },
                        new
                        {
                            Id = 6,
                            BasePrice = 5000m,
                            CategoryId = 9,
                            Description = "نیاز به توضیحات تکمیلی مشکل",
                            ImagePath = "\\Images\\HomeServices\\6h.jpg",
                            IsDeleted = false,
                            Title = "نصب و تعمیر شیرآلات"
                        },
                        new
                        {
                            Id = 7,
                            BasePrice = 4000m,
                            CategoryId = 9,
                            Description = "",
                            ImagePath = "\\Images\\HomeServices\\7h.jpg",
                            IsDeleted = false,
                            Title = "تخلیه چاه و لوله بازکنی"
                        },
                        new
                        {
                            Id = 8,
                            BasePrice = 1000m,
                            CategoryId = 9,
                            Description = "",
                            ImagePath = "\\Images\\HomeServices\\8h.jpg",
                            IsDeleted = false,
                            Title = "نصب و تعمیر دستگاه تصفیه آب"
                        },
                        new
                        {
                            Id = 9,
                            BasePrice = 2000m,
                            CategoryId = 9,
                            Description = "",
                            ImagePath = "\\Images\\HomeServices\\9h.jpg",
                            IsDeleted = false,
                            Title = "لوله کشی گاز"
                        },
                        new
                        {
                            Id = 10,
                            BasePrice = 4000m,
                            CategoryId = 9,
                            Description = "به صورت تخصصی",
                            ImagePath = "\\Images\\HomeServices\\10h.jpg",
                            IsDeleted = false,
                            Title = "اتصال به شبکه فاضلاب شهری"
                        },
                        new
                        {
                            Id = 11,
                            BasePrice = 1000m,
                            CategoryId = 8,
                            Description = "به صورت تخصصی",
                            ImagePath = "\\Images\\HomeServices\\11h.png",
                            IsDeleted = false,
                            Title = "سیم و کابل کشی"
                        },
                        new
                        {
                            Id = 12,
                            BasePrice = 3500m,
                            CategoryId = 8,
                            Description = "",
                            ImagePath = "\\Images\\HomeServices\\12h.jpg",
                            IsDeleted = false,
                            Title = "رفع اتصالی"
                        },
                        new
                        {
                            Id = 13,
                            BasePrice = 1000m,
                            CategoryId = 8,
                            Description = "",
                            ImagePath = "\\Images\\HomeServices\\13h.jpg",
                            IsDeleted = false,
                            Title = "کلید و پریز"
                        },
                        new
                        {
                            Id = 14,
                            BasePrice = 3500m,
                            CategoryId = 8,
                            Description = "",
                            ImagePath = "\\Images\\HomeServices\\14h.jpg",
                            IsDeleted = false,
                            Title = "نصب و تعویض فیوز"
                        },
                        new
                        {
                            Id = 15,
                            BasePrice = 2000m,
                            CategoryId = 8,
                            Description = "",
                            ImagePath = "\\Images\\HomeServices\\15h.jpg",
                            IsDeleted = false,
                            Title = "نصب و تعمیر دوربین مداربسته"
                        },
                        new
                        {
                            Id = 29,
                            BasePrice = 1000m,
                            CategoryId = 14,
                            Description = "",
                            ImagePath = "\\Images\\HomeServices\\29h.jpg",
                            IsDeleted = false,
                            Title = "سرویس عادی نظافت"
                        },
                        new
                        {
                            Id = 30,
                            BasePrice = 3500m,
                            CategoryId = 14,
                            Description = "",
                            ImagePath = "\\Images\\HomeServices\\30h.jpg",
                            IsDeleted = false,
                            Title = "سرویس لوکس نظافت"
                        },
                        new
                        {
                            Id = 31,
                            BasePrice = 2000m,
                            CategoryId = 14,
                            Description = "",
                            ImagePath = "\\Images\\HomeServices\\31h.jpg",
                            IsDeleted = false,
                            Title = "پذیرایی"
                        },
                        new
                        {
                            Id = 32,
                            BasePrice = 1000m,
                            CategoryId = 14,
                            Description = "",
                            ImagePath = "\\Images\\HomeServices\\32h.jpg",
                            IsDeleted = false,
                            Title = "کارگر ساده"
                        },
                        new
                        {
                            Id = 33,
                            BasePrice = 3500m,
                            CategoryId = 14,
                            Description = "",
                            ImagePath = "\\Images\\HomeServices\\33h.jpg",
                            IsDeleted = false,
                            Title = "نظافت راه پله"
                        },
                        new
                        {
                            Id = 34,
                            BasePrice = 1000m,
                            CategoryId = 15,
                            Description = "(فرش ، موکت ، مبل)",
                            ImagePath = "",
                            IsDeleted = false,
                            Title = "شستشو در منزل"
                        },
                        new
                        {
                            Id = 35,
                            BasePrice = 3500m,
                            CategoryId = 15,
                            Description = "",
                            ImagePath = "",
                            IsDeleted = false,
                            Title = "قالیشویی"
                        },
                        new
                        {
                            Id = 36,
                            BasePrice = 2000m,
                            CategoryId = 15,
                            Description = "",
                            ImagePath = "",
                            IsDeleted = false,
                            Title = "خشکشویی"
                        },
                        new
                        {
                            Id = 37,
                            BasePrice = 1000m,
                            CategoryId = 15,
                            Description = "",
                            ImagePath = "",
                            IsDeleted = false,
                            Title = "پرده شویی"
                        },
                        new
                        {
                            Id = 38,
                            BasePrice = 1000m,
                            CategoryId = 16,
                            Description = "(آب ، نانو)",
                            ImagePath = "",
                            IsDeleted = false,
                            Title = "کارواش"
                        },
                        new
                        {
                            Id = 39,
                            BasePrice = 3500m,
                            CategoryId = 16,
                            Description = "",
                            ImagePath = "",
                            IsDeleted = false,
                            Title = "صفرشویی خودرو"
                        },
                        new
                        {
                            Id = 40,
                            BasePrice = 2000m,
                            CategoryId = 16,
                            Description = "جدید",
                            ImagePath = "",
                            IsDeleted = false,
                            Title = "سرامیک حودرو"
                        },
                        new
                        {
                            Id = 41,
                            BasePrice = 1000m,
                            CategoryId = 16,
                            Description = "",
                            ImagePath = "",
                            IsDeleted = false,
                            Title = "واکس و پولیش"
                        },
                        new
                        {
                            Id = 42,
                            BasePrice = 3500m,
                            CategoryId = 16,
                            Description = "به صورت تخصصی",
                            ImagePath = "",
                            IsDeleted = false,
                            Title = "صافکاری و نقاشی"
                        },
                        new
                        {
                            Id = 43,
                            BasePrice = 1000m,
                            CategoryId = 17,
                            Description = "",
                            IsDeleted = false,
                            Title = "خدمات ناخن"
                        },
                        new
                        {
                            Id = 44,
                            BasePrice = 3500m,
                            CategoryId = 17,
                            Description = "",
                            IsDeleted = false,
                            Title = " رنگ مو در منزل"
                        },
                        new
                        {
                            Id = 45,
                            BasePrice = 2000m,
                            CategoryId = 17,
                            Description = "جدید",
                            IsDeleted = false,
                            Title = "پاکسازی و لایه برداری پوست"
                        },
                        new
                        {
                            Id = 46,
                            BasePrice = 1000m,
                            CategoryId = 17,
                            Description = "",
                            IsDeleted = false,
                            Title = "آرایش صورت در منزل"
                        },
                        new
                        {
                            Id = 47,
                            BasePrice = 3500m,
                            CategoryId = 17,
                            Description = "",
                            IsDeleted = false,
                            Title = "لیفت و لیمنت مژه"
                        },
                        new
                        {
                            Id = 48,
                            BasePrice = 1000m,
                            CategoryId = 18,
                            Description = "",
                            IsDeleted = false,
                            Title = "کوتاهی مو و اصلاح صورت"
                        },
                        new
                        {
                            Id = 49,
                            BasePrice = 3500m,
                            CategoryId = 18,
                            Description = "",
                            IsDeleted = false,
                            Title = "مراقب و زیبایی آقایان"
                        },
                        new
                        {
                            Id = 50,
                            BasePrice = 2000m,
                            CategoryId = 18,
                            Description = "",
                            IsDeleted = false,
                            Title = "گریم داماد"
                        },
                        new
                        {
                            Id = 51,
                            BasePrice = 1000m,
                            CategoryId = 19,
                            Description = "به صورت تخصصی",
                            IsDeleted = false,
                            Title = "برنامه ورزشی و تغذیه"
                        },
                        new
                        {
                            Id = 52,
                            BasePrice = 3500m,
                            CategoryId = 19,
                            Description = "",
                            IsDeleted = false,
                            Title = "کلاس یوگا در خانه"
                        },
                        new
                        {
                            Id = 53,
                            BasePrice = 2000m,
                            CategoryId = 19,
                            Description = "",
                            IsDeleted = false,
                            Title = "کلاس پیلاتس در خانه"
                        },
                        new
                        {
                            Id = 54,
                            BasePrice = 1000m,
                            CategoryId = 19,
                            Description = "جدید",
                            IsDeleted = false,
                            Title = "کلاس سی ایکس در خانه"
                        },
                        new
                        {
                            Id = 55,
                            BasePrice = 3500m,
                            CategoryId = 19,
                            Description = "",
                            IsDeleted = false,
                            Title = "حرکات اصلاحی"
                        },
                        new
                        {
                            Id = 56,
                            BasePrice = 1000m,
                            CategoryId = 20,
                            Description = "",
                            IsDeleted = false,
                            Title = "نصب و تعمیر یخچال فریزر"
                        },
                        new
                        {
                            Id = 57,
                            BasePrice = 3500m,
                            CategoryId = 20,
                            Description = "",
                            IsDeleted = false,
                            Title = " نصب و تعمیر ماشین ظرفشویی"
                        },
                        new
                        {
                            Id = 58,
                            BasePrice = 2000m,
                            CategoryId = 20,
                            Description = "",
                            IsDeleted = false,
                            Title = "نصب و تعمیر ماشین لباسشویی"
                        },
                        new
                        {
                            Id = 59,
                            BasePrice = 1000m,
                            CategoryId = 20,
                            Description = "",
                            IsDeleted = false,
                            Title = "نصب و تعمیر فر"
                        },
                        new
                        {
                            Id = 60,
                            BasePrice = 3500m,
                            CategoryId = 20,
                            Description = "",
                            IsDeleted = false,
                            Title = "نصب و تعمیر هود آشپرخانه"
                        },
                        new
                        {
                            Id = 61,
                            BasePrice = 1000m,
                            CategoryId = 20,
                            Description = "",
                            IsDeleted = false,
                            Title = "نصب و تعمیر اجاق گاز"
                        },
                        new
                        {
                            Id = 62,
                            BasePrice = 3500m,
                            CategoryId = 20,
                            Description = "به صورت تخصصی",
                            IsDeleted = false,
                            Title = " تعمیرات تلویزیون"
                        },
                        new
                        {
                            Id = 63,
                            BasePrice = 2000m,
                            CategoryId = 20,
                            Description = "جدید",
                            IsDeleted = false,
                            Title = "تعمیر چای ساز و قهوه ساز"
                        },
                        new
                        {
                            Id = 64,
                            BasePrice = 1000m,
                            CategoryId = 20,
                            Description = "",
                            IsDeleted = false,
                            Title = "تعمیر جاروبرقی"
                        },
                        new
                        {
                            Id = 65,
                            BasePrice = 3500m,
                            CategoryId = 20,
                            Description = "",
                            IsDeleted = false,
                            Title = "نصب و تعویض فیلتر آب"
                        },
                        new
                        {
                            Id = 66,
                            BasePrice = 1000m,
                            CategoryId = 21,
                            Description = "",
                            IsDeleted = false,
                            Title = "تعمیر کامپیوتر و لپتاپ"
                        },
                        new
                        {
                            Id = 67,
                            BasePrice = 3500m,
                            CategoryId = 21,
                            Description = "",
                            IsDeleted = false,
                            Title = " تعمیر ماشین های اداری"
                        },
                        new
                        {
                            Id = 68,
                            BasePrice = 2000m,
                            CategoryId = 21,
                            Description = "",
                            IsDeleted = false,
                            Title = "پشتیبانی شبکه وسرور"
                        },
                        new
                        {
                            Id = 69,
                            BasePrice = 1000m,
                            CategoryId = 21,
                            Description = "به صورت تخصصی",
                            IsDeleted = false,
                            Title = "طراحی سایت و لوگو"
                        },
                        new
                        {
                            Id = 70,
                            BasePrice = 3500m,
                            CategoryId = 21,
                            Description = "",
                            IsDeleted = false,
                            Title = "مودم و اینترنت"
                        },
                        new
                        {
                            Id = 71,
                            BasePrice = 1000m,
                            CategoryId = 22,
                            Description = "",
                            IsDeleted = false,
                            Title = "خدمات تاچ و ال سی دی"
                        },
                        new
                        {
                            Id = 72,
                            BasePrice = 3500m,
                            CategoryId = 22,
                            Description = "",
                            IsDeleted = false,
                            Title = " خدمات باتری"
                        },
                        new
                        {
                            Id = 73,
                            BasePrice = 2000m,
                            CategoryId = 22,
                            Description = "جدید",
                            IsDeleted = false,
                            Title = "خدمات نرم افزاری"
                        },
                        new
                        {
                            Id = 74,
                            BasePrice = 1000m,
                            CategoryId = 22,
                            Description = "",
                            IsDeleted = false,
                            Title = "خدمات اسپیکر"
                        },
                        new
                        {
                            Id = 75,
                            BasePrice = 3500m,
                            CategoryId = 22,
                            Description = "",
                            IsDeleted = false,
                            Title = "خدمات دوربین"
                        },
                        new
                        {
                            Id = 76,
                            BasePrice = 1000m,
                            CategoryId = 23,
                            Description = "زیر قیمت کارخانه",
                            IsDeleted = false,
                            Title = "تعویض باتری خودرو"
                        },
                        new
                        {
                            Id = 77,
                            BasePrice = 3500m,
                            CategoryId = 23,
                            Description = "",
                            IsDeleted = false,
                            Title = " برق و باتری خودرو"
                        },
                        new
                        {
                            Id = 78,
                            BasePrice = 2000m,
                            CategoryId = 23,
                            Description = "",
                            IsDeleted = false,
                            Title = "مکانیکی خودرو"
                        },
                        new
                        {
                            Id = 79,
                            BasePrice = 1000m,
                            CategoryId = 23,
                            Description = "",
                            IsDeleted = false,
                            Title = "امداد خودرو"
                        },
                        new
                        {
                            Id = 80,
                            BasePrice = 3500m,
                            CategoryId = 23,
                            Description = "",
                            IsDeleted = false,
                            Title = "پنچرگیری"
                        },
                        new
                        {
                            Id = 81,
                            BasePrice = 1000m,
                            CategoryId = 23,
                            Description = "",
                            IsDeleted = false,
                            Title = "کارشناسی خودرو"
                        },
                        new
                        {
                            Id = 82,
                            BasePrice = 3500m,
                            CategoryId = 23,
                            Description = "",
                            IsDeleted = false,
                            Title = "تعویض لاستیک"
                        },
                        new
                        {
                            Id = 83,
                            BasePrice = 2000m,
                            CategoryId = 23,
                            Description = "",
                            IsDeleted = false,
                            Title = "تعویض لنت خودرو"
                        },
                        new
                        {
                            Id = 84,
                            BasePrice = 1000m,
                            CategoryId = 23,
                            Description = "",
                            IsDeleted = false,
                            Title = "سوخت رسانی"
                        },
                        new
                        {
                            Id = 85,
                            BasePrice = 3500m,
                            CategoryId = 23,
                            Description = "",
                            IsDeleted = false,
                            Title = "تعمیر موتور سیکلت"
                        },
                        new
                        {
                            Id = 86,
                            BasePrice = 1000m,
                            CategoryId = 24,
                            Description = "",
                            IsDeleted = false,
                            Title = "اسباب کشی با خاور و کامیون"
                        },
                        new
                        {
                            Id = 87,
                            BasePrice = 3500m,
                            CategoryId = 24,
                            Description = "",
                            IsDeleted = false,
                            Title = " اسباب کشی با وانت و نیسان"
                        },
                        new
                        {
                            Id = 88,
                            BasePrice = 2000m,
                            CategoryId = 24,
                            Description = "نیاز به توضیح",
                            IsDeleted = false,
                            Title = "اسباب کشی و حمل بین شهری"
                        },
                        new
                        {
                            Id = 89,
                            BasePrice = 1000m,
                            CategoryId = 24,
                            Description = "",
                            IsDeleted = false,
                            Title = "کارگر جابجایی"
                        },
                        new
                        {
                            Id = 90,
                            BasePrice = 3500m,
                            CategoryId = 24,
                            Description = "",
                            IsDeleted = false,
                            Title = "حمل نخاله و ضایعات ساختمانی"
                        },
                        new
                        {
                            Id = 91,
                            BasePrice = 1000m,
                            CategoryId = 25,
                            Description = "",
                            IsDeleted = false,
                            Title = "مراقبت و نگهداری"
                        },
                        new
                        {
                            Id = 92,
                            BasePrice = 3500m,
                            CategoryId = 25,
                            Description = "",
                            IsDeleted = false,
                            Title = " پرستاری و تزریقات"
                        },
                        new
                        {
                            Id = 93,
                            BasePrice = 2000m,
                            CategoryId = 25,
                            Description = "",
                            IsDeleted = false,
                            Title = "معاینه پزشکی"
                        },
                        new
                        {
                            Id = 94,
                            BasePrice = 1000m,
                            CategoryId = 25,
                            Description = "",
                            IsDeleted = false,
                            Title = "پیراپزشکی"
                        },
                        new
                        {
                            Id = 95,
                            BasePrice = 3500m,
                            CategoryId = 25,
                            Description = "",
                            IsDeleted = false,
                            Title = "آزمایش و نمونه گیری"
                        },
                        new
                        {
                            Id = 96,
                            BasePrice = 1000m,
                            CategoryId = 26,
                            Description = "جدید",
                            IsDeleted = false,
                            Title = "هتل های حیوانات خانگی"
                        },
                        new
                        {
                            Id = 97,
                            BasePrice = 3500m,
                            CategoryId = 26,
                            Description = "",
                            IsDeleted = false,
                            Title = " خدماتدامپزشکی در محل"
                        },
                        new
                        {
                            Id = 98,
                            BasePrice = 2000m,
                            CategoryId = 26,
                            Description = "به صورت تخصصی",
                            IsDeleted = false,
                            Title = "خدمات تربیتی حیوانات خانگی"
                        },
                        new
                        {
                            Id = 99,
                            BasePrice = 1000m,
                            CategoryId = 26,
                            Description = "",
                            IsDeleted = false,
                            Title = "خدمات شستشو و آرایشی"
                        },
                        new
                        {
                            Id = 100,
                            BasePrice = 3500m,
                            CategoryId = 26,
                            Description = "",
                            IsDeleted = false,
                            Title = "پت شاپ"
                        });
                });

            modelBuilder.Entity("App.Domain.Core.Entites.User.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("App.Domain.Core.Entites.User.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int?>("ActivationUser")
                        .HasColumnType("int");

                    b.Property<int?>("AdminId")
                        .HasColumnType("int");

                    b.Property<float>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(1000f);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("RegisterAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ActivationUser = 3,
                            Balance = 1000f,
                            ConcurrencyStamp = "ae948b8b-6807-4c5d-a42b-92d4a147e808",
                            EmailConfirmed = false,
                            FirstName = "Admin",
                            IsDeleted = false,
                            LastName = "Admin",
                            LockoutEnabled = false,
                            Password = "123456",
                            PasswordHash = "AQAAAAIAAYagAAAAEC6Z7Ykd5EU9fF1U1uQpQcIoh61Ii+FtDl0nm1CCsJr3MwM4AZFgnvZLEcgY3g6eKg==",
                            PhoneNumberConfirmed = false,
                            RegisterAt = new DateTime(2025, 2, 25, 9, 56, 13, 814, DateTimeKind.Local).AddTicks(4691),
                            RoleId = 1,
                            SecurityStamp = "6df3cc69-2b99-43de-acef-9f77faa58c5e",
                            TwoFactorEnabled = false,
                            UserName = "Admin@gmail.com"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ActivationUser = 3,
                            Balance = 1000f,
                            ConcurrencyStamp = "11c11ca2-09f6-4f15-b8fd-9fcf741c0b73",
                            EmailConfirmed = false,
                            FirstName = "Amir",
                            IsDeleted = false,
                            LastName = "Amiri",
                            LockoutEnabled = false,
                            Password = "456789",
                            PasswordHash = "AQAAAAIAAYagAAAAEJ7iH17nEfvlxrRzd1qHlDfljvu1oDg8Sr7xmRl1ckxrLwbreOazbH9gRBTxMfnGhQ==",
                            PhoneNumberConfirmed = false,
                            RegisterAt = new DateTime(2025, 2, 25, 9, 56, 13, 814, DateTimeKind.Local).AddTicks(4759),
                            RoleId = 2,
                            SecurityStamp = "9f791466-0db3-422b-b9f0-3cb365e28e87",
                            TwoFactorEnabled = false,
                            UserName = "Customer@gmail.com"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ActivationUser = 3,
                            Balance = 1000f,
                            ConcurrencyStamp = "8dd7cbc8-3f89-4865-9875-101e9c6a2855",
                            EmailConfirmed = false,
                            FirstName = "Amir",
                            IsDeleted = false,
                            LastName = "Amiri",
                            LockoutEnabled = false,
                            Password = "258852",
                            PasswordHash = "AQAAAAIAAYagAAAAEICPdGBx7yS+fvKsuTFBRspMIegk0bcs8wUI7pCT6IsMZ0aYz8LXCaa5oqsfA6DiSQ==",
                            PhoneNumberConfirmed = false,
                            RegisterAt = new DateTime(2025, 2, 25, 9, 56, 13, 814, DateTimeKind.Local).AddTicks(4771),
                            RoleId = 3,
                            SecurityStamp = "41fe0230-e263-4848-9441-0a7c262fe5bf",
                            TwoFactorEnabled = false,
                            UserName = "Expert@gmail.com"
                        });
                });

            modelBuilder.Entity("App.Domain.Core.Entites.User.Customer", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasMaxLength(255)
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "اینجا",
                            CityId = 1,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("App.Domain.Core.Entites.User.Expert", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Biographi")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("Points")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Expert", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "اینجا",
                            Biographi = "بیوگرافی",
                            CityId = 1,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "تهران"
                        },
                        new
                        {
                            Id = 2,
                            Name = "مشهد"
                        },
                        new
                        {
                            Id = 3,
                            Name = "اصفهان"
                        },
                        new
                        {
                            Id = 4,
                            Name = "شیراز"
                        },
                        new
                        {
                            Id = 5,
                            Name = "تبریز"
                        },
                        new
                        {
                            Id = 6,
                            Name = "کرج"
                        },
                        new
                        {
                            Id = 7,
                            Name = "قم"
                        },
                        new
                        {
                            Id = 8,
                            Name = "اهواز"
                        },
                        new
                        {
                            Id = 9,
                            Name = "رشت"
                        },
                        new
                        {
                            Id = 10,
                            Name = "کرمانشاه"
                        },
                        new
                        {
                            Id = 11,
                            Name = "زاهدان"
                        },
                        new
                        {
                            Id = 12,
                            Name = "ارومیه"
                        },
                        new
                        {
                            Id = 13,
                            Name = "یزد"
                        },
                        new
                        {
                            Id = 14,
                            Name = "همدان"
                        },
                        new
                        {
                            Id = 15,
                            Name = "قزوین"
                        },
                        new
                        {
                            Id = 16,
                            Name = "سنندج"
                        },
                        new
                        {
                            Id = 17,
                            Name = "بندرعباس"
                        },
                        new
                        {
                            Id = 18,
                            Name = "زنجان"
                        },
                        new
                        {
                            Id = 19,
                            Name = "ساری"
                        },
                        new
                        {
                            Id = 20,
                            Name = "بوشهر"
                        },
                        new
                        {
                            Id = 21,
                            Name = "مازندران"
                        },
                        new
                        {
                            Id = 22,
                            Name = "گرگان"
                        },
                        new
                        {
                            Id = 23,
                            Name = "کرمان"
                        },
                        new
                        {
                            Id = 24,
                            Name = "خرم آباد"
                        },
                        new
                        {
                            Id = 25,
                            Name = "سمنان"
                        });
                });

            modelBuilder.Entity("Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExpertId")
                        .HasColumnType("int");

                    b.Property<int?>("ExpertRating")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPlayable")
                        .HasColumnType("bit");

                    b.Property<string>("Opinion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Points")
                        .HasColumnType("int");

                    b.Property<int?>("stausService")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExpertId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = new DateTime(2025, 2, 25, 9, 56, 13, 812, DateTimeKind.Local).AddTicks(8928),
                            ExpertId = 1,
                            IsDeleted = false,
                            IsPlayable = true,
                            Opinion = "بسیار تمیز و بادقت",
                            Points = 9
                        },
                        new
                        {
                            Id = 2,
                            CreateAt = new DateTime(2025, 2, 25, 9, 56, 13, 812, DateTimeKind.Local).AddTicks(8939),
                            ExpertId = 1,
                            IsDeleted = false,
                            IsPlayable = true,
                            Opinion = "تحویل به موقع",
                            Points = 9
                        },
                        new
                        {
                            Id = 3,
                            CreateAt = new DateTime(2025, 2, 25, 9, 56, 13, 812, DateTimeKind.Local).AddTicks(8942),
                            ExpertId = 1,
                            IsDeleted = false,
                            IsPlayable = true,
                            Opinion = "پاسخگویی بد",
                            Points = 6
                        });
                });

            modelBuilder.Entity("Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HouseWorkId")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("HouseWorkId")
                        .IsUnique();

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Expert",
                            NormalizedName = "EXPERT"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("ExpertId")
                        .HasColumnType("int");

                    b.Property<int>("HouseWorkId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsConfrim")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsFinish")
                        .HasColumnType("bit");

                    b.Property<TimeOnly>("RunningTime")
                        .HasColumnType("time");

                    b.Property<int>("StausService")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ExpertId");

                    b.HasIndex("HouseWorkId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompletionDate = new DateTime(2025, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateAt = new DateTime(2025, 2, 25, 9, 56, 13, 812, DateTimeKind.Local).AddTicks(3573),
                            CustomerId = 1,
                            Description = "فوری",
                            HouseWorkId = 5,
                            IsDeleted = false,
                            RunningTime = new TimeOnly(0, 0, 0).Add(TimeSpan.FromTicks(11)),
                            StausService = 1
                        },
                        new
                        {
                            Id = 2,
                            CompletionDate = new DateTime(2025, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateAt = new DateTime(2025, 2, 25, 9, 56, 13, 812, DateTimeKind.Local).AddTicks(3599),
                            CustomerId = 1,
                            Description = "",
                            HouseWorkId = 6,
                            IsDeleted = false,
                            RunningTime = new TimeOnly(10, 30, 0),
                            StausService = 1
                        },
                        new
                        {
                            Id = 3,
                            CompletionDate = new DateTime(2025, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateAt = new DateTime(2025, 2, 25, 9, 56, 13, 812, DateTimeKind.Local).AddTicks(3605),
                            CustomerId = 1,
                            Description = "فوری",
                            HouseWorkId = 30,
                            IsDeleted = false,
                            RunningTime = new TimeOnly(4, 30, 0),
                            StausService = 1
                        });
                });

            modelBuilder.Entity("Suggestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DeliverDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("ExpertId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExpertId");

                    b.HasIndex("OrderId");

                    b.ToTable("Suggestions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeliverDate = new DateTime(2025, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "آمادگی برای انجام کار با قیمت پایین تر",
                            ExpertId = 1,
                            IsDeleted = false,
                            OrderId = 1
                        });
                });

            modelBuilder.Entity("App.Domain.Core.Entites.Service.Category", b =>
                {
                    b.HasOne("App.Domain.Core.Entites.Service.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("App.Domain.Core.Entites.Service.ExpertHouseWork", b =>
                {
                    b.HasOne("App.Domain.Core.Entites.User.Expert", "Expert")
                        .WithMany("ExpertWorksSkills")
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Domain.Core.Entites.Service.HouseWork", "HouseWork")
                        .WithMany("ExpertHouseWorks")
                        .HasForeignKey("HouseWorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expert");

                    b.Navigation("HouseWork");
                });

            modelBuilder.Entity("App.Domain.Core.Entites.Service.HouseWork", b =>
                {
                    b.HasOne("App.Domain.Core.Entites.Service.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("App.Domain.Core.Entites.User.AppUser", b =>
                {
                    b.HasOne("App.Domain.Core.Entites.User.Admin", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId");

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("App.Domain.Core.Entites.User.Customer", b =>
                {
                    b.HasOne("City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("App.Domain.Core.Entites.User.AppUser", "User")
                        .WithOne("Customer")
                        .HasForeignKey("App.Domain.Core.Entites.User.Customer", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("User");
                });

            modelBuilder.Entity("App.Domain.Core.Entites.User.Expert", b =>
                {
                    b.HasOne("City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("App.Domain.Core.Entites.User.AppUser", "User")
                        .WithOne("Expert")
                        .HasForeignKey("App.Domain.Core.Entites.User.Expert", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Comment", b =>
                {
                    b.HasOne("App.Domain.Core.Entites.User.Expert", "Expert")
                        .WithMany()
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Expert");
                });

            modelBuilder.Entity("Image", b =>
                {
                    b.HasOne("App.Domain.Core.Entites.Service.HouseWork", "HouseWork")
                        .WithOne("Image")
                        .HasForeignKey("Image", "HouseWorkId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("HouseWork");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("App.Domain.Core.Entites.User.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("App.Domain.Core.Entites.User.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Domain.Core.Entites.User.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("App.Domain.Core.Entites.User.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Order", b =>
                {
                    b.HasOne("App.Domain.Core.Entites.User.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("App.Domain.Core.Entites.User.Expert", "Expert")
                        .WithMany()
                        .HasForeignKey("ExpertId");

                    b.HasOne("App.Domain.Core.Entites.Service.HouseWork", "HouseWork")
                        .WithMany("Orders")
                        .HasForeignKey("HouseWorkId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Expert");

                    b.Navigation("HouseWork");
                });

            modelBuilder.Entity("Suggestion", b =>
                {
                    b.HasOne("App.Domain.Core.Entites.User.Expert", "Expert")
                        .WithMany("Suggestions")
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Order", "Order")
                        .WithMany("Suggestions")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Expert");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("App.Domain.Core.Entites.Service.Category", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("App.Domain.Core.Entites.Service.HouseWork", b =>
                {
                    b.Navigation("ExpertHouseWorks");

                    b.Navigation("Image")
                        .IsRequired();

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("App.Domain.Core.Entites.User.AppUser", b =>
                {
                    b.Navigation("Customer");

                    b.Navigation("Expert");
                });

            modelBuilder.Entity("App.Domain.Core.Entites.User.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("App.Domain.Core.Entites.User.Expert", b =>
                {
                    b.Navigation("ExpertWorksSkills");

                    b.Navigation("Suggestions");
                });

            modelBuilder.Entity("Order", b =>
                {
                    b.Navigation("Suggestions");
                });
#pragma warning restore 612, 618
        }
    }
}
